# Generated by Django 3.1.7 on 2021-06-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='daily_posts_add_counter',
            field=models.SmallIntegerField(default=0),
        ),
    ]
