# Generated by Django 3.1.7 on 2021-09-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_auto_20210924_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(help_text='название категории', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name_en_us',
            field=models.CharField(help_text='название категории', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(help_text='название категории', max_length=30, null=True, unique=True),
        ),
    ]
