# Generated by Django 3.1.7 on 2021-05-24 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_auto_20210409_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы (чтоб переопр. название - см. класс Meta в модели)'},
        ),
    ]
