# Generated by Django 3.1.7 on 2021-06-08 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newapp', '0004_auto_20210409_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscriber',
            field=models.ManyToManyField(related_name='subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
