# Generated by Django 3.2 on 2021-06-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_auto_20210609_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='category',
        ),
    ]
