# Generated by Django 3.2 on 2021-06-10 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_rename_category_name_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='newapp.post'),
        ),
    ]
