# Generated by Django 3.2.8 on 2021-11-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=250, verbose_name='Сообщение')),
                ('dt_message', models.DateTimeField(verbose_name='Дата сообщения')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Объявление')),
                ('category', models.CharField(choices=[('Tanks', 'Танки'), ('Hils', 'Хилы'), ('DD', 'ДД'), ('Merchants', 'Торговцы'), ('Gildmasters', 'Гилдмастеры'), ('Questgivers', 'Квестгиверы'), ('Blacksmith', 'Кузнецы'), ('Tanners', 'Кожевники'), ('PotionMakers', 'Зельевары'), ('CraftsmenSpells', 'Мастера заклинаний')], max_length=50, verbose_name='Категория')),
                ('dt_post', models.DateTimeField(verbose_name='Дата поста')),
            ],
        ),
    ]
