# Generated by Django 3.2.8 on 2021-11-06 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='category_post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='text_post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='title_post',
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
