# Generated by Django 3.2.8 on 2021-11-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_auto_20211106_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
    ]
